$iOSVersion = '12.0'

platform :ios, $iOSVersion
use_frameworks!

target 'AWSKinesisVideoWebRTCDemoApp' do
  pod 'AWSCognitoIdentityProvider'
  pod 'AWSMobileClient'
  pod 'CommonCryptoModule'
  pod 'AWSKinesisVideo'
  pod 'AWSKinesisVideoSignaling'
  pod 'GoogleWebRTC', '~> 1.1'
  pod 'Starscream', '~> 3.0'
  	target 'AWSKinesisVideoWebRTCDemoAppUITests' do
  	  inherit! :complete
  	end
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = $iOSVersion
            end
        end
    end
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
        end
    end
    installer.pods_project.build_configurations.each do |config|
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = $iOSVersion
    end
end
